### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Clazex** [royitaqi/HollowKnight.GodhomeWinLossTracker#1]
Like what Pantheons Hit Counter does
Not only normal localization but also "localizing" raw scene name into respective boss name

**Comment by royitaqi** [comment]
Yeah thx for the good item. I was thinking about it (correct English boss name and support multi-language).

~~Pantheons Hit Counter didn't do localization (in the multi-language sense), right? I thought it only got the English boss names from a .json file (e.g. no Chinese). Let me try.~~ It does. I will mimic.

**Comment by royitaqi** [comment]
Correct English boss names (instead of scene names) implemented in 694700830a265174b107c04bdb3273ce86b2a2c7.

Localization of the notification will take more time, because it involves not only the localized boss names, but also the language used in the notification, e.g. "Won <Boss Name> in <Sequence Name>". Take it as P1.
